language: python

after_success:
    - bash <(curl -s https://codecov.io/bash)

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

# install dependencies
install:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt

# run unitttest
script:
    - python test/extracellular_unittest.py 
